package com.cisdi.ext.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * @author 尹涛 * @version V1.0.0
 * @projectName cisdi-pms-service
 * @title FileCodeEnum
 * @package com.cisdi.ext.enums
 * @description
 * @date 2022/8/29
 */
@Getter
@AllArgsConstructor
public enum FileCodeEnum {

    // 立项申请
    APPROVE_PROJECT("APPROVE_PROJECT", "立项申请", "1"),
    PRJ_REQ_FILE("PRJ_REQ_FILE", "项目申请材料", "1"),
    STAMPED_PRJ_REQ_FILE("STAMPED_PRJ_REQ_FILE", "盖章立项申请书", "2"),
    REPLY_FILE("REPLY_FILE", "立项批复文件", "3"),

    // 可研估算
    FEASIBLE_ESTIMATE("FEASIBLE_ESTIMATE", "可研估算", "2"),
    PM_PRJ_FILE("PM_PRJ_FILE", "可研申请材料", "1"),
    KY_REVISION_FILE("KY_REVISION_FILE", "修编稿文件", "2"),
    KY_REVIEW_DRAFT_FILE("KY_REVIEW_DRAFT_FILE", "评审报告文件", "3"),
    KY_REVIEW_REPORT_FILE("KY_REVIEW_REPORT_FILE", "评审稿文件", "4"),
    KY_EXPERT_FILE("KY_EXPERT_FILE", "专家意见文件", "5"),
    FEASIBLE_REPLY_FILE("FEASIBLE_REPLY_FILE", "可研批复文件", "6"),

    // 初设概算
    BEGINNING_ESTIMATE("BEGINNING_ESTIMATE", "初设概算", "3"),
    BUDGETESTIMATEDECLARATION_FILE("BUDGETESTIMATEDECLARATION_FILE", "概算申报材料", "1"),
    GS_REVIEW_REPORT_FILE("REVIEW_REPORT_FILE", "初概报告评审稿", "2"),
    GS_EXPERT_FILE("EXPERT_FILE", "初概报告专家意见", "3"),
    GS_REVISION_FILE("REVISION_FILE", "初概报告修编稿", "4"),
    GS_REPLY_FILE("REPLY_FILE", "概算批复", "5"),

    // 预算财评
    BUDGET_MONEY_RATING("BUDGET_MONEY_RATING", "预算财评", "4"),
    APPLICATION_MATERIALS("APPLICATION_MATERIALS", "财评申报材料", "1"),
    WORK_DRAWING_TO_REVIEW_FILE("WORK_DRAWING_TO_REVIEW_FILE", "施工图预算送审稿", "2"),
    BUDGET_REVIEW_CONCLUSION_FILE("BUDGET_REVIEW_CONCLUSION_FILE", "预算审核结论书", "3"),
    FINANCIAL_REVIEW_FILE("FINANCIAL_REVIEW_FILE", "财评批复", "4"),

    // 采购招标
    PURCHASE_TENDER("PURCHASE_TENDER", "采购招标", "5"),
    BID_DEMAND_FILE_GROUP("BID_DEMAND_FILE_GROUP", "招标需求附件", "1"),
    LEADER_APPROVE_FILE_GROUP("LEADER_APPROVE_FILE_GROUP", "领导审批附件", "2"),
    BID_FILE_GROUP("BID_FILE_GROUP", "招标文件", "3"),
    BID_ISSUE_FILE_GROUP("BID_ISSUE_FILE_GROUP", "发标招标文件", "4"),
    BID_AFTER_FILE_GROUP("BID_AFTER_FILE_GROUP", "标后附件", "5"),
    BID_WIN_NOTICE_FILE_GROUP("BID_WIN_NOTICE_FILE_GROUP", "标后通知书", "6"),
    PURCHASE_TENDER_PROCESS_ATTACHMENT("PURCHASE_TENDER_PROCESS_ATTACHMENT", "采购公开招标流程附件", "7"),

    // 采购合同
    PURCHASE_CONTRACT("PURCHASE_CONTRACT", "采购合同", "6"),
    ATT_FILE_GROUP("ATT_FILE_GROUP", "合同附件", "1"),
    SUBJECT_FILE("SUBJECT_FILE", "主体材料", "2"),
    GUARANTEE_RESULT_FILE("GUARANTEE_RESULT_FILE", "保函结果材料", "3"),
    CONTRACT_HISTORY("CONTRACT_HISTORY", "合同历史", "4"),

    // 采购合同补充协议申请
    PO_ORDER_SUPPLEMENT_REQ("PO_ORDER_SUPPLEMENT_REQ", "采购合同补充协议申请", "5"),
    SUPPLEMENTARY_AGREEMENT_ATTACHMENT("SUPPLEMENTARY_AGREEMENT_ATTACHMENT", "补充协议附件", "1"),
    PO_ORDER_SUPPLEMENT_REQ_PROCESS_ATTACHMENT("PO_ORDER_SUPPLEMENT_REQ_PROCESS_ATTACHMENT", "采购合同补充协议申请流程附件", "2"),

    // 采购合同变更申请
    PO_ORDER_CHANGE_REQ("PO_ORDER_CHANGE_REQ", "采购合同变更申请", "6"),
    CHANGE_ATTACHMENTS("CHANGE_ATTACHMENTS", "变更附件", "1"),
    PO_ORDER_CHANGE_REQ_PROCESS_ATTACHMENT("PO_ORDER_CHANGE_REQ_PROCESS_ATTACHMENT", "采购合同变更申请流程附件", "2"),

    // 采购合同终止申请
    CONTRACT_TERMINATION_REQ("CONTRACT_TERMINATION_REQ", "采购合同终止申请", "7"),
    CONTRACT_TERMINATION_APPENDIX("CONTRACT_TERMINATION_APPENDIX", "合同终止附件", "1"),
    CONTRACT_TERMINATION_REQ_PROCESS_ATTACHMENT("CONTRACT_TERMINATION_REQ_PROCESS_ATTACHMENT", "采购合同终止申请流程附件", "2"),

    // 合同签订
    PO_ORDER_REQ("PO_ORDER_REQ", "合同签订", "8"),
    PO_ORDER_REQ_ATT_FILE_GROUP_ID("PO_ORDER_REQ_ATT_FILE_GROUP_ID", "合同文本", "1"),
    PO_ORDER_REQ_FILE_ID_TWO("PO_ORDER_REQ_FILE_ID_TWO", "财务部门修订稿", "2"),
    PO_ORDER_REQ_FILE_ID_THREE("PO_ORDER_REQ_FILE_ID_THREE", "法务部门修订稿", "3"),
    PO_ORDER_REQ_FILE_ID_FOUR("PO_ORDER_REQ_FILE_ID_FOUR", "采纳意见附件", "4"),
    PO_ORDER_REQ_FILE_ID_ONE("PO_ORDER_REQ_FILE_ID_ONE", "合同送审稿", "5"),
    PO_ORDER_REQ_FILE_ID_FIVE("PO_ORDER_REQ_FILE_ID_TWO", "经办人上传盖章版合同", "6"),

    // 水保
    WATER_PLAN("WATER_PLAN", "水保", "7"),
    WATER_SOIL_CONSERVATION_APPLICATION_MATERIAL("WATER_SOIL_CONSERVATION_APPLICATION_MATERIAL", "水保申请材料", "1"),
    EIA_REPLY_DOCUMENT("EIA_REPLY_DOCUMENT", "环评批复文件", "2"),
    WATER_PLAN_PROCESS_ATTACHMENT("WATER_PLAN_PROCESS_ATTACHMENT", "水保流程附件", "3"),

    // 工程规划许可
    PROJECT_PLANNING_PERMIT("PROJECT_PLANNING_PERMIT", "工程规划许可", "8"),
    SCHEME_DESIGN_VERIFICATION_APPLICATION_MATERIALS("SCHEME_DESIGN_VERIFICATION_APPLICATION_MATERIALS", "方案设计核查申请材料", "1"),
    SCHEME_DESIGN_REVIEW_OFFICE("SCHEME_DESIGN_REVIEW_OFFICE", "方案设计评审搞", "2"),
    SCHEME_DESIGN_EXPERT_OPINIONS("SCHEME_DESIGN_EXPERT_OPINIONS", "方案设计专家意见", "3"),
    SCHEME_DESIGN_REVISED_DRAFT("SCHEME_DESIGN_REVISED_DRAFT", "方案设计修编稿", "4"),
    SCHEME_CHECK_PPT_FILE("SCHEME_CHECK_PPT_FILE", "方案检查ppt文件", "5"),
    ADMINISTRATION_REVIEW_MEETING_COMMITTEE_OPINIONS("ADMINISTRATION_REVIEW_MEETING_COMMITTEE_OPINIONS", "管理局预审会市委会意见", "6"),
    PLANNING_COMMITTEE_REVIEW_MEETING_OPINIONS("PLANNING_COMMITTEE_REVIEW_MEETING_OPINIONS", "规委会预审会市委会意见", "7"),
    DEPUTY_MAYOR_REVIEW_MEETING_OPINIONS("DEPUTY_MAYOR_REVIEW_MEETING_OPINIONS", "分管副市长预审会市委会意见", "8"),
    MAYOR_REVIEW_MEETING_OPINIONS("MAYOR_REVIEW_MEETING_OPINIONS", "分管副市长和市长预审会市委会意见", "9"),
    MUNICIPAL_PLANNING_COMMISSION_OPINIONS("MUNICIPAL_PLANNING_COMMISSION_OPINIONS", "市规委会意见", "10"),
    PROJECT_PLANNING_PERMIT_APPLICATION_MATERIALS("PROJECT_PLANNING_PERMIT_APPLICATION_MATERIALS", "工程规划许可申请材料", "11"),
    PROJECT_PLANNING_LICENCE("PROJECT_PLANNING_LICENCE", "工程规划许可证", "12"),
    PROJECT_PLANNING_PERMIT_PROCESS_ATTACHMENT("PROJECT_PLANNING_PERMIT_PROCESS_ATTACHMENT", "工程规划许可流程附件", "13"),

    // 开工申请
    COMMENCEMENT_APPLICATION("COMMENCEMENT_APPLICATION", "开工申请", "9"),
    COMMENCEMENT_APPLICATION_ATTACHMENT("COMMENCEMENT_APPLICATION_ATTACHMENT", "开工申请附件", "1"),
    COMMENCEMENT_APPLICATION_PROCESS_ATTACHMENT("COMMENCEMENT_APPLICATION_PROCESS_ATTACHMENT", "开工申请流程附件", "2"),

    // 资金管理
    FUND_MANAGEMENT("FUND_MANAGEMENT", "资金管理", "10"),
    FUND_PLAN_FILE("FUND_PLAN_FILE", "资金需求计划文件", "1"),
    FUND_SOURCE_FILE("FUND_SOURCE_FILE", "资金来源文件", "2"),
    FUND_APPORTION_FILE("FUND_APPORTION_FILE", "资金分配文件", "3"),
    FUND_PAY_FILE("FUND_PAY_FILE", "资金支付文件", "4"),
    //资金需求计划申请
    PM_FUND_REQUIRE_PLAN_REQ("PM_FUND_REQUIRE_PLAN_REQ","资金需求计划申请","5"),
    CAPITAL_DEMAND_PLAN_APPROVAL_DOCUMENT("REPLY_FILE","资金需求计划批复文件","1"),
    BUDGET_REVIEW_APPROVAL_DOCUMENT("CONSERVATION_REPLY_FILE","预算评审批复文件","2"),
    CONSTRUCTION_ACCEPTANCE_LETTER("BID_WIN_NOTICE_FILE_GROUP_ID","施工中标通知书","3"),
    COMMENCEMENT_ORDER_ATTACHMENT("ATT_FILE_GROUP_ID","开工令附件","4"),
    FORMAL_CONTRACT_ANNEX("BID_AFTER_FILE_GROUP_ID","正式合同附件","5"),

    //其他流程
    OTHERS("OTHERS","其他流程","100"),
    //概念方案设计管理
    PM_CONCEPTUAL_SCHEME_DESIGN("PM_CONCEPTUAL_SCHEME_DESIGN","概念方案设计管理","1"),
    CONCEPTUAL_RENDERING_ONE("DESIGN_SKETCH_FILE_ONE","效果图1","1"),
    CONCEPTUAL_SCHEME_DESIGN_SPECIFICATION_ONE("APPROVE_FILE_ID_ONE","概念方案设计任务书1","2"),
    CONCEPTUAL_RENDERING_TWO("DESIGN_SKETCH_FILE_TWO","效果图2","3"),
    CONCEPTUAL_SCHEME_DESIGN_SPECIFICATION_TWO("APPROVE_FILE_ID_TWO","概念方案设计任务书2","4"),
    CONCEPTUAL_RENDERING_THREE("DESIGN_SKETCH_FILE_THREE","效果图3","5"),
    CONCEPTUAL_SCHEME_DESIGN_SPECIFICATION_THREE("APPROVE_FILE_ID_THREE","概念方案设计任务书3","6"),
    CONCEPTUAL_SCHEME_DESIGN_RESULT_FILE("APPROVE_FILE_ID_FOUR","概念方案设计成果","7"),

    //设计任务书
    PM_DESIGN_ASSIGNMENT_BOOK("PM_DESIGN_ASSIGNMENT_BOOK","设计任务书","2"),
    DESIGN_SPECIFICATION_ATTACHMENT("ATT_FILE_GROUP_ID","附件","1"),
    DESIGN_SPECIFICATION_ATTACHMENT_ONE("APPROVE_FILE_ID_ONE","审批附件1","2"),
    DESIGN_SPECIFICATION_ATTACHMENT_TWO("APPROVE_FILE_ID_TWO","审批附件2","3"),
    DESIGN_SPECIFICATION_ATTACHMENT_THREE("APPROVE_FILE_ID_THREE","审批附件3","4"),

    //方案设计管理
    PM_DESIGN_ASSIGNMENT("PM_DESIGN_ASSIGNMENT","方案设计管理","3"),
    SCHEMATIC_DESIGN_MANAGEMENT_RENDERING("DESIGN_SKETCH_FILE_ONE","效果图","1"),
    DESIGN_MANAGEMENT_CONCEPTUAL_SCHEME_DESIGN_RESULT("ATT_FILE_GROUP_ID","概念方案设计成果","2"),

    //施工图设计管理
    PM_CONSTRUCTION_DRAWING_DESIGN("PM_CONSTRUCTION_DRAWING_DESIGN","施工图设计管理","4"),
    CONSTRUCTION_DRAWING_DESIGN_MANAGEMENT_RENDERING("DESIGN_SKETCH_FILE_ONE","效果图","1"),
    CONSTRUCTION_DRAWING_CONCEPTUAL_DESIGN_RESULT("ATT_FILE_GROUP_ID","概念方案设计成果","2"),

    //施工许可
    PM_CONSTRUCT_PERMIT_REQ("PM_CONSTRUCT_PERMIT_REQ","施工许可","5"),
    FOUNDATION_PIT_EARTHWORK_APPLICATION("PRJ_REQ_FILE","基坑及土石方工程申请","1"),
    MAIN_WORKS_APPLICATION("KEEP_RECORD_FILE","主体工程申请","2"),
    EARTHWORK_FILE("EARTHWORK_FILE","基坑及土石方工程施工许可函","3"),

    //社会稳定性评价
    PM_STABLE_EVAL("PM_STABLE_EVAL","社会稳定性评价","6"),
    SOCIAL_STABILITY_RISK_ASSESSMENT_REPORT("KEEP_RECORD_FILE","社会稳定性风险评估报告","1"),

    //固定资产投资节能评价
    PM_ENERGY_EVAL("PM_ENERGY_EVAL","固定资产投资节能评价","7"),
    FIXED_ASSETS_INVESTMENT_SAVING_REPORT("KEEP_RECORD_FILE","固定资产投资节能评估报告","1"),
    ENERGY_SAVING_REPORT_REVIEW_DRAFT("REVIEW_REPORT_FILE","节能报告评审稿","2"),
    ENERGY_SAVING_REPORT_EXPERT_OPINION("EXPERT_FILE","节能报告专家意见","3"),
    EIA_APPROVAL_DOCUMENT("REPLY_FILE","环评批复文件","4"),

    //环评
    PM_ENVIRONMENT_EVAL("PM_ENVIRONMENT_EVAL","环评","8"),
    EIA_APPLICATION_MATERIAL("EIA_REQ_FILE","环评申请材料","1"),
    EIA_REPORT_REVIEW_DRAFT("REVIEW_REPORT_FILE","环评报告评审稿","2"),
    EIA_REPORT_EXPERT_OPINION("EXPERT_FILE"," 环评报告专家意见","3"),
    REVISION_OF_EIA_REPORT("REVISION_FILE","环评报告修编稿","4"),
    EIA_APPROVAL_FILE("CONSERVATION_REPLY_FILE","环评批复文件","5"),

    //农转用手续办理
    PM_FARMING_PROCEDURES("PM_FARMING_PROCEDURES","农转用手续办理","9"),
    AGRICULTURAL_CONVERSION_PROCEDURES_ANNEX("ATT_FILE_GROUP_ID","农转用手续附件","1"),
    SURVEY_DELIMITATION_MATERIALS("SUBJECT_FILE","勘测定界材料","2"),
    AGRICULTURAL_CONVERSION_APPROVAL_DOCUMENT("APPROVE_FILE_ID_ONE","农转用批复文件","3"),

    //林地调整办理手续
    PM_WOODLAND_PROCEDURES("PM_WOODLAND_PROCEDURES","林地调整办理手续","10"),
    FOREST_LAND_HANDLING_AUDIT_ATTACHMENT("ATT_FILE_GROUP_ID","林地办理审核附件","1"),
    SURVEY_DELIMITATION_REPORT("SUBJECT_FILE","勘测定界报告","2"),
    FOREST_LAND_FEASIBILITY_PRE_REPORT("APPROVE_FILE_ID_ONE","林地使用可行性报告评审前","3"),
    FOREST_FEASIBILITY_EXPERT_OPINIONS("APPROVE_FILE_ID_TWO","林地使用可行性报告专家意见","4"),
    FOREST_LAND_USE_FEASIBILITY_REPORT("APPROVE_FILE_ID_THREE","林地使用可行性报告","5"),
    FOREST_LAND_USE_CONSENT("APPROVE_FILE_ID_FOUR","林地使用同意书","6"),

    //用地规划许可
    PM_LAND_USE_REQ("PM_LAND_USE_REQ","用地规划许可","11"),
    RED_LINE_VERIFICATION_OPINIONS("APPROVE_FILE_ID_FOUR","红线核查意见书","1"),
    LAND_USE_SURVEY_AND_DELIMITATION_MATERIALS("APPROVE_FILE_ID_ONE","用地勘测定界材料","2"),
    LAND_ACQUISITION_INVESTIGATION_REPORT("APPROVE_FILE_ID_TWO","征地调查报告","3"),
    LAND_USE_PLANNING_PERMIT("APPROVE_FILE_ID_THREE","用地规划许可证","4"),

    //招标核准
    PM_TENDER_VERIFICATION("PM_TENDER_VERIFICATION","招标核准","12"),
    BIDDING_APPROVAL_APPLICATION_ATTACHMENT("APPROVE_FILE_ID_ONE","招标核准申请附件","1"),
    APPROVAL_OF_BIDDING_APPENDIX("APPROVE_FILE_ID_TWO","招标核准批复附件","2"),

    //征地调查
    PM_LAND_EXAMINE_REQ("PM_LAND_EXAMINE_REQ","征地调查","13"),
    INVESTIGATION_DOCUMENTS("APPROVE_FILE_ID_ONE","调查文件","1"),
    APPROVED_BOUNDARY_MATERIALS("APPROVE_FILE_ID_TWO","核定界限材料","2"),
    COILING_MATERIALS("APPROVE_FILE_ID_THREE","组卷材料","3"),
    LAND_ACQUISITION_INVESTIGATION_APPROVAL_MATERIALS("APPROVE_FILE_ID_FOUR","征地调查批复材料","4"),

    //土地证办理
    PM_LAND_CERTIFICATE("PM_LAND_CERTIFICATE","土地证办理","14"),
    LAND_ALLOCATION_DECISION("ATT_FILE_GROUP_ID","土地划拨决定书","1"),
    LAND_CERTIFICATE("APPROVE_FILE_ID_ONE","土地证","2"),

    //人防规划报建
    PM_DEFENSE_PLAN_REQ("PM_DEFENSE_PLAN_REQ","人防规划报建","15"),
    CIVIL_AIR_DEFENSE_PLANNING_APPLICATION("APPROVE_FILE_ID_ONE","人防规划核准申请附件","1"),
    CIVIL_AIR_DEFENSE_ROLL_FORMING_MATERIALS("APPROVE_FILE_ID_TWO","人防组卷材料","2"),
    CIVIL_AIR_DEFENSE_PLANNING_APPROVAL_MATERIALS("APPROVE_FILE_ID_THREE","人防规划批复材料","3"),

    //人防施工报建
    PM_DEFENSE_BUILD_REQ("PM_DEFENSE_BUILD_REQ","人防施工报建","16"),
    CIVIL_AIR_DEFENSE_CONSTRUCTION_APPLICATION_DATA("ATT_FILE_GROUP_ID","人防施工报建资料","1"),
    OPINIONS_ON_CIVIL_AIR_DEFENSE_CONSTRUCTION_SURVEY("APPROVE_FILE_ID_ONE","人防施工踏勘意见书","2"),
    CIVIL_AIR_DEFENSE_CONSTRUCTION_DATA_REVISION("APPROVE_FILE_ID_TWO","人防施工资料修编版","3"),
    CIVIL_AIR_DEFENSE_CONSTRUCT_APP_MATERIAL("APPROVE_FILE_ID_THREE","人防施工申请资料","4"),
    CIVIL_AIR_DEFENSE_CONSTRUCT_APP_FILING("KEEP_RECORD_FILE","人防施工报建备案","5"),

    //国安报建
    PM_NATIONAL_BUILD_REQ("PM_NATIONAL_BUILD_REQ","国安报建","17"),
    NATIONAL_SECURITY_APPLICATION_PLAN("ATT_FILE_GROUP_ID","国安批复文件","1"),
    NATIONAL_SECURITY_APPROVAL_DOCUMENT("APPROVE_FILE_ID_ONE","国安批复文件","2"),

    //白蚁防治
    PM_TERMITE_CONTROL_REQ("PM_TERMITE_CONTROL_REQ","白蚁防治","18"),
    TERMITE_CONTROL_PLAN("ATT_FILE_GROUP_ID","白蚁防治方案","1"),
    TERMITE_CONTROL_PLAN_FILING("APPROVE_FILE_ID_ONE","白蚁防治方案备案","2"),
    TERMITE_CONTROL_IMPLEMENT_ATTACHMENT("APPROVE_FILE_ID_TWO","白蚁防治实施附件","3"),
    TERMITE_CONTROL_ACCEPTANCE_ATTACHMENT("APPROVE_FILE_ID_THREE","白蚁防治验收附件","4"),

    //耕作层剥离
    PM_TOPSOIL_STRIPPING_REQ("PM_TOPSOIL_STRIPPING_REQ","耕作层剥离","19"),
    TOPSOIL_STRIP_REVIEW_ATTACHMENT("ATT_FILE_GROUP_ID","耕作层剥离审核附件","1"),
    TOPSOIL_STRIP_PLAN_PREPARATION_RESULTS("APPROVE_FILE_ID_ONE","耕作层剥离方案编制成果","2"),
    TOPSOIL_STRIP_IMPLEMENT_REVIEW_DRAFT("APPROVE_FILE_ID_TWO","耕作层剥离实施评审稿","3"),
    TOPSOIL_STRIPPING_EXPERT_OPINION("APPROVE_FILE_ID_THREE","耕作层剥离专家意见","4"),
    FARMING_LAYER_STRIPPING_FILING("APPROVE_FILE_ID_FOUR","耕作层剥离备案","5"),
    TOPSOIL_STRIPPING_ACCEPTANCE("APPROVE_FILE_ID_FIVE","耕作层剥离验收","6"),

    //五方责任主体及终身质量承诺书
//    PM_PARTY_QUALITY_PROMISE_REQ("PM_PARTY_QUALITY_PROMISE_REQ","五方责任主体及终身质量承诺书","20"),
//    EMPLOYER_COMMITMENT_LETTER("EMPLOYER_COMMITMENT_LETTER","建设单位承诺书","1"),

    //监理规划及细则申请
    PM_SUPERVISE_PLAN_REQ("PM_SUPERVISE_PLAN_REQ","监理规划及细则申请","21"),
    SUPERVISION_PLANNING_ANNEX("ATT_FILE_GROUP_ID","监理规划附件","1"),

    //技术交底与图纸会审记录
    SKILL_DISCLOSURE_PAPER_RECHECK_RECORD("SKILL_DISCLOSURE_PAPER_RECHECK_RECORD","技术交底与图纸会审记录","22"),
    DRAWING_JOINT_REVIEW_ATTACHMENT("ATT_FILE_GROUP_ID","图纸会审附件","1"),

    //施工进度计划
    PM_BUILD_PROGRESS_REQ("PM_BUILD_PROGRESS_REQ","施工进度计划","23"),
    CONSTRUCTION_SCHEDULE_ATTACHMENT("ATT_FILE_GROUP_ID","施工进度计划附件","1"),

    //施工组织设计及施工方案
    PM_BUILD_ORGAN_PLAN_REQ("PM_BUILD_ORGAN_PLAN_REQ","施工组织设计及施工方案","24"),
    CONSTRUCTION_ORGANIZATION_DESIGN_ATTACHMENT("ATT_FILE_GROUP_ID","施工组织设计附件","1"),

    //工作联系单
    PM_WORK_LIST_REQ("PM_WORK_LIST_REQ","工作联系单","25"),
    WORK_CONTACT_LIST_ATTACHMENT("ATT_FILE_GROUP_ID","工作联系单附件","1"),

    //报审报验
    APPROVAL_INSPECTION("APPROVAL_INSPECTION","报审报验","26"),
    APPROVAL_INSPECTION_ATTACHMENT("ATT_FILE_GROUP_ID","报审报验附件","1"),

    //工程索赔通知书
    PROJECT_CLAIM_NOTICE("PROJECT_CLAIM_NOTICE","工程索赔通知书","27"),
    PROJECT_CLAIM_NOTICE_ATTACHMENTS("ATT_FILE_GROUP_ID","工程索赔通知书附件","1"),

    //费用索赔报审表
    EXPENSE_CLAIM_APPROVAL("EXPENSE_CLAIM_APPROVAL","费用索赔报审表","28"),
    EXPENSE_CLAIM_APPROVAL_FORM("ATT_FILE_GROUP_ID","费用索赔报审表附件","1"),

    //竣工预验收
    COMPLETION_PRE_ACCEPTANCE("COMPLETION_PRE_ACCEPTANCE","竣工预验收","29"),
    COMPLETION_PRE_ACCEPTANCE_ATTACHMENT("ATT_FILE_GROUP_ID","竣工预验收附件","1"),

    //质量交底记录
    QUALITY_RECORD("QUALITY_RECORD","质量交底记录","30"),
    QUALITY_RECORD_ATTACHMENT("ATT_FILE_GROUP_ID","质量交底记录附件","1"),

    //工程质量检查
    PROJECT_QUALITY_INSPECTION("PROJECT_QUALITY_INSPECTION","工程质量检查","31"),
    PROJECT_QUALITY_INSPECTION_MATERIALS("ATT_FILE_GROUP_ID","工程质量检查材料","1"),

    //科研材料设备进场验收
    SCIENTIFIC_MATERIAL_CHECK("SCIENTIFIC_MATERIAL_CHECK","科研材料设备进场验收","32"),
    SCIENTIFIC_MATERIAL_CHECK_ATTACHMENT("ATT_FILE_GROUP_ID","科研材料设备进场验收材料","1"),

    //合同品牌变更申请
    CONTRACT_BRAND_CHANGE_APPLICATION("CONTRACT_BRAND_CHANGE_APPLICATION","合同品牌变更申请","33"),
    CONTRACT_BRAND_CHANGE_APPLICATION_ATTACHMENT("ATT_FILE_GROUP_ID","合同品牌变更申请附件","1"),

    //工程材料设备及品牌报审
    MATERIAL_EQUIPMENT_BRAND_APPROVAL("MATERIAL_EQUIPMENT_BRAND_APPROVAL","工程材料设备及品牌报审","34"),
    MATERIAL_EQUIPMENT_BRAND_APPROVAL_ATTACHMENT("ATT_FILE_GROUP_ID","工程材料设备及品牌报审附件","1"),

    //工程材料设备进场验收
    MATERIAL_EQUIPMENT_ENTER_CHECK("MATERIAL_EQUIPMENT_ENTER_CHECK","工程材料设备进场验收","35"),
    MATERIAL_EQUIPMENT_ENTER_CHECK_ATTACHMENT("ATT_FILE_GROUP_ID","工程材料设备进场验收附件","1"),

    //材料退场
    PM_MATERIAL_EXIT("PM_MATERIAL_EXIT","材料退场","36"),
    PM_MATERIAL_EXIT_ATTACHMENT("PM_MATERIAL_EXIT","材料退场附件","1"),

    //工程付款申请
    PO_ORDER_PAYMENT_REQ("PO_ORDER_PAYMENT_REQ","工程付款申请","37"),
    PROJECT_PAYMENT_APPLICATION("ATT_FILE_GROUP_ID","工程付款申请附件","1"),
    PROJECT_PAYMENT_CONTENT_ATTACHMENT("SUBJECT_FILE","工程付款内容","2"),
    PROJECT_PAYMENT_GUARANTEE_CONTENTS("GUARANTEE_RESULT_FILE","工程付款保函内容","3"),

    //新增保函申请
    PO_GUARANTEE_LETTER_REQUIRE_REQ("PO_GUARANTEE_LETTER_REQUIRE_REQ","新增保函申请","38"),
    GUARANTEE_FORMAL_CONTRACT("ATT_FILE_GROUP_ID","保函正式合同","1"),
    FORMAL_GUARANTEE("GUARANTEE_FILE","正式保函","2"),
    GUARANTEE_RESULT("GUARANTEE_RESULT_FILE","保函结果","3"),

    //保函退还申请
    PO_GUARANTEE_LETTER_RETURN_REQ("PO_GUARANTEE_LETTER_RETURN_REQ","保函退还申请","39"),
    GUARANTEE_RETURN_LETTER_ANNEX("GUARANTEE_FILE","保函退还附件","1"),

    //用章审批
    APPROVAL_WITH_SEAL("APPROVAL_WITH_SEAL","用章审批","40"),
    APPROVAL_WITH_SEAL_ATTACHMENT("ATT_FILE_GROUP_ID","用章审批附件","1"),

    //防洪评价
    PM_CONTROL_FLOOD_REQ("PM_CONTROL_FLOOD_REQ","防洪评价","41"),
    FLOOD_CONTROL_PLAN_MATERIALS("APPROVE_FILE_ID_ONE","防洪方案材料","1"),
    FLOOD_CONTROL_APPROVAL_DOCUMENTS("APPROVE_FILE_ID_TWO","防洪批复文件","2"),

    //交通安全评价
    PM_TRAFFIC_SAFETY_REQ("PM_TRAFFIC_SAFETY_REQ","交通安全评价","42"),
    TRAFFIC_SAFETY_PLAN_MATERIALS("APPROVE_FILE_ID_ONE","交通安全方案材料","1"),
    TRAFFIC_SAFETY_PLAN_FILING("APPROVE_FILE_ID_TWO","交通安全方案备案","2"),

    //土地划拨
    PM_LAND_ALLOCATION_REQ("PM_LAND_ALLOCATION_REQ","土地划拨","43"),
    LAND_ALLOCATION_SURVEY_REPORT("APPROVE_FILE_ID_ONE","土地划拨调查报告","1"),
    LAND_ALLOCATION_DECISION_APPLICATION_MATERIALS("APPROVE_FILE_ID_TWO","土地划拨决定书申请材料","2"),
    LAND_ALLOCATION_DECISION_REPLY("APPROVE_FILE_ID_THREE","土地划拨决定书批复","3"),

    //标前资料用印审批
    PM_FILE_CHAPTER_REQ("PM_FILE_CHAPTER_REQ","标前资料用印审批","44"),
    PM_FILE_CHAPTER_REQ_FILE_ID_ONE("FILE_ID_ONE","招标文件","1"),
    PM_FILE_CHAPTER_REQ_FILE_ID_TWO("FILE_ID_TWO","标前资料","2"),


    //招标文件审批
    PM_BID_APPROVAL_REQ("PM_BID_APPROVAL_REQ", "招标文件审批", "45"),
    PM_BID_APPROVAL_REQ_FILE_ID_ONE("PM_BID_APPROVAL_REQ_FILE_ID_ONE", "招标文件", "1"),
    PM_BID_APPROVAL_REQ_FILE_ID_TWO("PM_BID_APPROVAL_REQ_FILE_ID_TWO", "招标文件终稿", "2"),

    //采购需求审批
    PM_BUY_DEMAND_REQ("PM_BUY_DEMAND_REQ", "采购需求审批", "46"),
    PM_BUY_DEMAND_REQ_FILE_ID_ONE("PM_BUY_DEMAND_REQ_FILE_ID_ONE", "采购需求说明书", "1"),
    PM_BUY_DEMAND_REQ_FILE_ID_TWO("PM_BUY_DEMAND_REQ_FILE_ID_TWO", "采购预算表", "2"),
    PM_BUY_DEMAND_REQ_FILE_ID_THREE("PM_BUY_DEMAND_REQ_FILE_ID_THREE", "采购启动依据文件", "3"),

    //工程暂停令
    PM_PRJ_STOP_ORDER_REQ("PM_PRJ_STOP_ORDER_REQ", "工程暂停令", "47"),
    PM_PRJ_STOP_ORDER_REQ_FILE_ID_ONE("PM_PRJ_STOP_ORDER_REQ_FILE_ID_ONE", "附件", "1"),

    //竣工联合验收意见
    COMPLETION_ACCEPTANCE_COMMENTS("COMPLETION_ACCEPTANCE_COMMENTS","竣工联合验收意见","48"),
    ACCEPTANCE_PREPARE_ATTACHMENTS("APPROVE_FILE_ID_ONE","资料准备附件","1"),
    COMPLETION_ACCEPTANCE_FILING_ATTACHMENT("APPROVE_FILE_ID_TWO","备案申报附件","2"),
    FILING_APPROVAL_ATTACHMENT("APPROVE_FILE_ID_THREE","备案批复附件","3"),
    DATA_VOLUME_ATTACHMENT("APPROVE_FILE_ID_FOUR","资料组卷附件","4"),
    JOINT_OPINION_DECLARATION_ATTACHMENT("APPROVE_FILE_ID_FIVE","联合意见申报","5"),
    JOINT_ACCEPTANCE_APPROVAL_ATTACHMENT("APPROVE_FILE_ID_SIX","联合验收批复","6"),

    //工程开工令
    PM_PRJ_RESTART_ORDER_REQ("PM_PRJ_RESTART_ORDER_REQ", "工程复工令", "49"),
    PM_PRJ_RESTART_ORDER_REQ_FILE_ID_ONE("PM_PRJ_RESTART_ORDER_REQ_FILE_ID_ONE", "附件", "1"),

    //分包单位资质报审
    SUBCONTRACTOR_QUALIFICATION_REPORT("SUBCONTRACTOR_QUALIFICATION_REPORT","分包单位资质报审","50"),
    QUALIFICATION_REPORT_ATTACHMENT("CONTRACT_FILE_GROUP_ID","资质报审附件","1"),

    //工程复工报审表
    PM_PRJ_RESTART_TRIAL_REQ("PM_PRJ_RESTART_TRIAL_REQ","工程复工报审表","51"),
    PM_PRJ_RESTART_TRIAL_REQ_FILE_ID_ONE("PM_PRJ_RESTART_TRIAL_REQ_FILE_ID_ONE","附件","1"),

    //设计变更
    PM_DESIGN_CHANGE_REQ("PM_DESIGN_CHANGE_REQ","设计变更","52"),
    PM_DESIGN_CHANGE_REQ_ATT_FILE_GROUP_ID("PM_DESIGN_CHANGE_REQ_ATT_FILE_GROUP_ID","附件","1"),

    //施工通知单
    PM_SUPERVISE_NOTICE_REQ("PM_SUPERVISE_NOTICE_REQ","施工通知单","53"),
    PM_SUPERVISE_NOTICE_REQ_ATT_FILE_GROUP_ID("PM_SUPERVISE_NOTICE_REQ_ATT_FILE_GROUP_ID","附件","1"),

    //施工通知回复单
    PM_SUPERVISE_NOTICE_REPLY_REQ("PM_SUPERVISE_NOTICE_REPLY_REQ","施工通知回复单","54"),
    PM_SUPERVISE_NOTICE_REPLY_REQ_ATT_FILE_GROUP_ID("PM_SUPERVISE_NOTICE_REPLY_REQ_ATT_FILE_GROUP_ID","附件","1"),

    ;
    private final String code;

    private final String des;

    private final String seq;
}
