package com.cisdi.ext.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * @author 尹涛 * @version V1.0.0
 * @projectName cisdi-pms-service
 * @title FileCodeEnum
 * @package com.cisdi.ext.enums
 * @description
 * @date 2022/8/29
 */
@Getter
@AllArgsConstructor
public enum FileCodeEnum {

    // 立项申请
    APPROVE_PROJECT("APPROVE_PROJECT", "立项申请", "1"),
    PRJ_REQ_FILE("PRJ_REQ_FILE", "项目申请材料", "1"),
    STAMPED_PRJ_REQ_FILE("STAMPED_PRJ_REQ_FILE", "盖章立项申请书", "2"),
    REPLY_FILE("REPLY_FILE", "立项批复文件", "3"),

    // 可研估算
    FEASIBLE_ESTIMATE("FEASIBLE_ESTIMATE", "可研估算", "2"),
    PM_PRJ_FILE("PM_PRJ_FILE", "可研申请材料", "1"),
    KY_REVISION_FILE("KY_REVISION_FILE", "修编稿文件", "2"),
    KY_REVIEW_DRAFT_FILE("KY_REVIEW_DRAFT_FILE", "评审报告文件", "3"),
    KY_REVIEW_REPORT_FILE("KY_REVIEW_REPORT_FILE", "评审稿文件", "4"),
    KY_EXPERT_FILE("KY_EXPERT_FILE", "专家意见文件", "5"),
    FEASIBLE_REPLY_FILE("FEASIBLE_REPLY_FILE", "可研批复文件", "6"),

    // 初设概算
    BEGINNING_ESTIMATE("BEGINNING_ESTIMATE", "初设概算", "3"),
    BUDGETESTIMATEDECLARATION_FILE("BUDGETESTIMATEDECLARATION_FILE", "概算申报材料", "1"),
    GS_REVIEW_REPORT_FILE("REVIEW_REPORT_FILE", "初概报告评审稿", "2"),
    GS_EXPERT_FILE("EXPERT_FILE", "初概报告专家意见", "3"),
    GS_REVISION_FILE("REVISION_FILE", "初概报告修编稿", "4"),
    GS_REPLY_FILE("REPLY_FILE", "概算批复", "5"),

    // 预算财评
    BUDGET_MONEY_RATING("BUDGET_MONEY_RATING", "预算财评", "4"),
    APPLICATION_MATERIALS("APPLICATION_MATERIALS", "财评申报材料", "1"),
    WORK_DRAWING_TO_REVIEW_FILE("WORK_DRAWING_TO_REVIEW_FILE", "施工图预算送审稿", "2"),
    BUDGET_REVIEW_CONCLUSION_FILE("BUDGET_REVIEW_CONCLUSION_FILE", "预算审核结论书", "3"),
    FINANCIAL_REVIEW_FILE("FINANCIAL_REVIEW_FILE", "财评批复", "4"),

    // 采购招标
    PURCHASE_TENDER("PURCHASE_TENDER", "采购招标", "5"),
    BID_DEMAND_FILE_GROUP("BID_DEMAND_FILE_GROUP", "招标需求附件", "1"),
    LEADER_APPROVE_FILE_GROUP("LEADER_APPROVE_FILE_GROUP", "领导审批附件", "2"),
    BID_FILE_GROUP("BID_FILE_GROUP", "招标文件", "3"),
    BID_ISSUE_FILE_GROUP("BID_ISSUE_FILE_GROUP", "发标招标文件", "4"),
    BID_AFTER_FILE_GROUP("BID_AFTER_FILE_GROUP", "标后附件", "5"),
    BID_WIN_NOTICE_FILE_GROUP("BID_WIN_NOTICE_FILE_GROUP", "标后通知书", "6"),
    PURCHASE_TENDER_PROCESS_ATTACHMENT("PURCHASE_TENDER_PROCESS_ATTACHMENT", "采购公开招标流程附件", "7"),

    // 采购合同
    PURCHASE_CONTRACT("PURCHASE_CONTRACT", "采购合同", "6"),
    ATT_FILE_GROUP("ATT_FILE_GROUP", "合同附件", "1"),
    SUBJECT_FILE("SUBJECT_FILE", "主体材料", "2"),
    GUARANTEE_RESULT_FILE("GUARANTEE_RESULT_FILE", "保函结果材料", "3"),
    CONTRACT_HISTORY("CONTRACT_HISTORY", "合同历史", "4"),

    // 采购合同补充协议申请
    PO_ORDER_SUPPLEMENT_REQ("PO_ORDER_SUPPLEMENT_REQ", "采购合同补充协议申请", "5"),
    SUPPLEMENTARY_AGREEMENT_ATTACHMENT("SUPPLEMENTARY_AGREEMENT_ATTACHMENT", "补充协议附件", "1"),
    PO_ORDER_SUPPLEMENT_REQ_PROCESS_ATTACHMENT("PO_ORDER_SUPPLEMENT_REQ_PROCESS_ATTACHMENT", "采购合同补充协议申请流程附件", "2"),

    // 采购合同变更申请
    PO_ORDER_CHANGE_REQ("PO_ORDER_CHANGE_REQ", "采购合同变更申请", "6"),
    CHANGE_ATTACHMENTS("CHANGE_ATTACHMENTS", "变更附件", "1"),
    PO_ORDER_CHANGE_REQ_PROCESS_ATTACHMENT("PO_ORDER_CHANGE_REQ_PROCESS_ATTACHMENT", "采购合同变更申请流程附件", "2"),

    // 采购合同终止申请
    CONTRACT_TERMINATION_REQ("CONTRACT_TERMINATION_REQ", "采购合同终止申请", "7"),
    CONTRACT_TERMINATION_APPENDIX("CONTRACT_TERMINATION_APPENDIX", "合同终止附件", "1"),
    CONTRACT_TERMINATION_REQ_PROCESS_ATTACHMENT("CONTRACT_TERMINATION_REQ_PROCESS_ATTACHMENT", "采购合同终止申请流程附件", "2"),

    // 水保
    WATER_PLAN("WATER_PLAN", "水保", "7"),
    WATER_SOIL_CONSERVATION_APPLICATION_MATERIAL("WATER_SOIL_CONSERVATION_APPLICATION_MATERIAL", "水保申请材料", "1"),
    EIA_REPLY_DOCUMENT("EIA_REPLY_DOCUMENT", "环评批复文件", "2"),
    WATER_PLAN_PROCESS_ATTACHMENT("WATER_PLAN_PROCESS_ATTACHMENT", "水保流程附件", "3"),

    // 工程规划许可
    PROJECT_PLANNING_PERMIT("PROJECT_PLANNING_PERMIT", "工程规划许可", "8"),
    SCHEME_DESIGN_VERIFICATION_APPLICATION_MATERIALS("SCHEME_DESIGN_VERIFICATION_APPLICATION_MATERIALS", "方案设计核查申请材料", "1"),
    SCHEME_DESIGN_REVIEW_OFFICE("SCHEME_DESIGN_REVIEW_OFFICE", "方案设计评审搞", "2"),
    SCHEME_DESIGN_EXPERT_OPINIONS("SCHEME_DESIGN_EXPERT_OPINIONS", "方案设计专家意见", "3"),
    SCHEME_DESIGN_REVISED_DRAFT("SCHEME_DESIGN_REVISED_DRAFT", "方案设计修编稿", "4"),
    SCHEME_CHECK_PPT_FILE("SCHEME_CHECK_PPT_FILE", "方案检查ppt文件", "5"),
    ADMINISTRATION_REVIEW_MEETING_COMMITTEE_OPINIONS("ADMINISTRATION_REVIEW_MEETING_COMMITTEE_OPINIONS", "管理局预审会市委会意见", "6"),
    PLANNING_COMMITTEE_REVIEW_MEETING_OPINIONS("PLANNING_COMMITTEE_REVIEW_MEETING_OPINIONS", "规委会预审会市委会意见", "7"),
    DEPUTY_MAYOR_REVIEW_MEETING_OPINIONS("DEPUTY_MAYOR_REVIEW_MEETING_OPINIONS", "分管副市长预审会市委会意见", "8"),
    MAYOR_REVIEW_MEETING_OPINIONS("MAYOR_REVIEW_MEETING_OPINIONS", "分管副市长和市长预审会市委会意见", "9"),
    MUNICIPAL_PLANNING_COMMISSION_OPINIONS("MUNICIPAL_PLANNING_COMMISSION_OPINIONS", "市规委会意见", "10"),
    PROJECT_PLANNING_PERMIT_APPLICATION_MATERIALS("PROJECT_PLANNING_PERMIT_APPLICATION_MATERIALS", "工程规划许可申请材料", "11"),
    PROJECT_PLANNING_LICENCE("PROJECT_PLANNING_LICENCE", "工程规划许可证", "12"),
    PROJECT_PLANNING_PERMIT_PROCESS_ATTACHMENT("PROJECT_PLANNING_PERMIT_PROCESS_ATTACHMENT", "工程规划许可流程附件", "13"),

    // 开工申请
    COMMENCEMENT_APPLICATION("COMMENCEMENT_APPLICATION", "开工申请", "9"),
    COMMENCEMENT_APPLICATION_ATTACHMENT("COMMENCEMENT_APPLICATION_ATTACHMENT", "开工申请附件", "1"),
    COMMENCEMENT_APPLICATION_PROCESS_ATTACHMENT("COMMENCEMENT_APPLICATION_PROCESS_ATTACHMENT", "开工申请流程附件", "2"),

    // 资金管理
    FUND_MANAGEMENT("FUND_MANAGEMENT", "资金管理", "10"),
    FUND_PLAN_FILE("FUND_PLAN_FILE", "资金需求计划文件", "1"),
    FUND_SOURCE_FILE("FUND_SOURCE_FILE", "资金来源文件", "2"),
    FUND_APPORTION_FILE("FUND_APPORTION_FILE", "资金分配文件", "3"),
    FUND_PAY_FILE("FUND_PAY_FILE", "资金支付文件", "4"),

    //其他流程
    OTHERS("OTHERS","其他流程","100"),
    //概念方案设计管理
    PM_CONCEPTUAL_SCHEME_DESIGN("PM_CONCEPTUAL_SCHEME_DESIGN","概念方案设计管理","1"),
    CONCEPTUAL_RENDERING_ONE("DESIGN_SKETCH_FILE_ONE","效果图1","1"),
    CONCEPTUAL_SCHEME_DESIGN_SPECIFICATION_ONE("APPROVE_FILE_ID_ONE","概念方案设计任务书1","2"),
    CONCEPTUAL_RENDERING_TWO("DESIGN_SKETCH_FILE_TWO","效果图2","3"),
    CONCEPTUAL_SCHEME_DESIGN_SPECIFICATION_TWO("APPROVE_FILE_ID_TWO","概念方案设计任务书2","4"),
    CONCEPTUAL_RENDERING_THREE("DESIGN_SKETCH_FILE_THREE","效果图3","5"),
    CONCEPTUAL_SCHEME_DESIGN_SPECIFICATION_THREE("APPROVE_FILE_ID_THREE","概念方案设计任务书3","6"),
    CONCEPTUAL_SCHEME_DESIGN_RESULT_FILE("APPROVE_FILE_ID_FOUR","概念方案设计成果","7"),

    //设计任务书
    PM_DESIGN_ASSIGNMENT_BOOK("PM_DESIGN_ASSIGNMENT_BOOK","设计任务书","2"),
    DESIGN_SPECIFICATION_ATTACHMENT("ATT_FILE_GROUP_ID","附件","1"),
    DESIGN_SPECIFICATION_ATTACHMENT_ONE("APPROVE_FILE_ID_ONE","审批附件1","2"),
    DESIGN_SPECIFICATION_ATTACHMENT_TWO("APPROVE_FILE_ID_TWO","审批附件2","3"),
    DESIGN_SPECIFICATION_ATTACHMENT_THREE("APPROVE_FILE_ID_THREE","审批附件3","4"),

    //方案设计管理
    PM_DESIGN_ASSIGNMENT("PM_DESIGN_ASSIGNMENT","方案设计管理","3"),
    SCHEMATIC_DESIGN_MANAGEMENT_RENDERING("DESIGN_SKETCH_FILE_ONE","效果图","1"),
    DESIGN_MANAGEMENT_CONCEPTUAL_SCHEME_DESIGN_RESULT("ATT_FILE_GROUP_ID","概念方案设计成果","2"),

    //施工图设计管理
    PM_CONSTRUCTION_DRAWING_DESIGN("PM_CONSTRUCTION_DRAWING_DESIGN","施工图设计管理","4"),
    CONSTRUCTION_DRAWING_DESIGN_MANAGEMENT_RENDERING("DESIGN_SKETCH_FILE_ONE","效果图","1"),
    CONSTRUCTION_DRAWING_CONCEPTUAL_DESIGN_RESULT("ATT_FILE_GROUP_ID","概念方案设计成果","2")
    ;
    private final String code;

    private final String des;

    private final String seq;
}
